-- =============================================================================
-- 03_load_tables.sql (Snowflake)
-- Object : Loads the 9 stage files into 9 tables, strictly 1 CSV = 1 table
--          Every column is STRING, ALL columns kept in file order,
--          no union, no cast, no constraints.
--          Students pre-process the data themselves (Power Query / Tableau Prep).
-- Idempotent : Yes (CREATE OR REPLACE / DROP TABLE IF EXISTS)
-- Duration : ~1 minute on XSMALL Warehouse
-- =============================================================================

USE DATABASE EMLYON_USE_CASES;
USE WAREHOUSE EMLYON_WH;

-- =============================================================================
-- 0. LEGACY CLEANUP (previous RAW_* / FACT_* / DIM_* layers)
-- =============================================================================
DROP TABLE IF EXISTS GDP.FACT_LIFE_EXPECTANCY;
DROP TABLE IF EXISTS GDP.DIM_CONTINENT;
DROP TABLE IF EXISTS GDP.RAW_LIFE_EXPECTANCY;
DROP TABLE IF EXISTS GDP.RAW_CONTINENT_MAPPING;
DROP TABLE IF EXISTS SUPERSTORE.FACT_ORDERS;
DROP TABLE IF EXISTS SUPERSTORE.DIM_CATEGORY;
DROP TABLE IF EXISTS SUPERSTORE.RAW_ORDERS;
DROP TABLE IF EXISTS SUPERSTORE.RAW_NOMENCLATURE;
DROP TABLE IF EXISTS ALLSALES.FACT_ORDERS;
DROP TABLE IF EXISTS ALLSALES.DIM_SALES_TEAM;
DROP TABLE IF EXISTS ALLSALES.DIM_STORE;
DROP TABLE IF EXISTS ALLSALES.RAW_ORDERS;
DROP TABLE IF EXISTS ALLSALES.RAW_TEAM;
DROP TABLE IF EXISTS ALLSALES.RAW_STORE;

-- =============================================================================
-- USE CASE 1 : GDP
-- =============================================================================

-- 1.1 Life expectancy vs GDP (12,744 rows expected) ---------------------------
CREATE OR REPLACE TABLE GDP.LIFE_EXPECTANCY (
  CODE STRING,
  CONTINENT STRING,
  COUNTRY STRING,
  GDP_PER_CAPITA_ANNOTATIONS STRING,
  YEAR STRING,
  GDP STRING,
  LIFE_EXP STRING,
  POPULATION STRING
)
COMMENT = 'Source file life_expectancy.csv, as is. Decimal commas on Life exp.';

COPY INTO GDP.LIFE_EXPECTANCY
FROM @GDP.RAW_STAGE
FILES = ('life_expectancy.csv')
FILE_FORMAT = (FORMAT_NAME = 'GDP.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- 1.2 Continent mapping (3 rows expected) -------------------------------------
CREATE OR REPLACE TABLE GDP.CONTINENT_MAPPING (
  CONTINENT STRING,
  CODE_CONTINENT STRING
)
COMMENT = 'Source file continent_mapping.csv, as is. INTENTIONALLY INCOMPLETE (Europe, Asia, Mars).';

COPY INTO GDP.CONTINENT_MAPPING
FROM @GDP.RAW_STAGE
FILES = ('continent_mapping.csv')
FILE_FORMAT = (FORMAT_NAME = 'GDP.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- =============================================================================
-- USE CASE 2 : SUPERSTORE
-- part1 and part2 have DIFFERENT column orders: each table follows its own file.
-- =============================================================================

-- 2.1 Migration batch 1 (3,895 rows expected) ---------------------------------
CREATE OR REPLACE TABLE SUPERSTORE.SUPERSTORE_PART1 (
  CITY STRING,
  COUNTRY_REGION STRING,
  CUSTOMER_NAME STRING,
  MANUFACTURER STRING,
  ORDER_DATE STRING,
  ORDER_ID STRING,
  PRODUCT_NAME STRING,
  REMOVE_INC STRING,
  REMOVE_INC_2 STRING,
  REGION STRING,
  SEGMENT STRING,
  SHIP_DATE STRING,
  SHIP_MODE STRING,
  STATE_PROVINCE STRING,
  SUB_CATEGORY STRING,
  DISCOUNT STRING,
  PROFIT STRING,
  QUANTITY STRING,
  SALES STRING
)
COMMENT = 'Source file superstore_part1.csv, as is. Column order differs from part2.';

COPY INTO SUPERSTORE.SUPERSTORE_PART1
FROM @SUPERSTORE.RAW_STAGE
FILES = ('superstore_part1.csv')
FILE_FORMAT = (FORMAT_NAME = 'SUPERSTORE.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- 2.2 Migration batch 2 (6,105 rows expected) ---------------------------------
CREATE OR REPLACE TABLE SUPERSTORE.SUPERSTORE_PART2 (
  COUNTRY_REGION STRING,
  CITY STRING,
  CUSTOMER_NAME STRING,
  MANUFACTURER STRING,
  ORDER_DATE STRING,
  ORDER_ID STRING,
  PRODUCT_NAME STRING,
  REGION STRING,
  REMOVE_INC STRING,
  REMOVE_INC_2 STRING,
  SEGMENT STRING,
  SHIP_DATE STRING,
  SHIP_MODE STRING,
  STATE_PROVINCE STRING,
  SUB_CATEGORY STRING,
  DISCOUNT STRING,
  PROFIT STRING,
  QUANTITY STRING,
  SALES STRING
)
COMMENT = 'Source file superstore_part2.csv, as is. Column order differs from part1.';

COPY INTO SUPERSTORE.SUPERSTORE_PART2
FROM @SUPERSTORE.RAW_STAGE
FILES = ('superstore_part2.csv')
FILE_FORMAT = (FORMAT_NAME = 'SUPERSTORE.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- 2.3 Category nomenclature (17 rows expected) --------------------------------
CREATE OR REPLACE TABLE SUPERSTORE.NOMENCLATURE (
  CATEGORY STRING,
  SUB_CATEGORY STRING
)
COMMENT = 'Source file nomenclature.csv, as is. Prefixed categories (1-Office Supplies).';

COPY INTO SUPERSTORE.NOMENCLATURE
FROM @SUPERSTORE.RAW_STAGE
FILES = ('nomenclature.csv')
FILE_FORMAT = (FORMAT_NAME = 'SUPERSTORE.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- =============================================================================
-- USE CASE 3 : ALLSALES
-- =============================================================================

-- 3.1 Sales batch 2025 (20,000 rows expected) ---------------------------------
CREATE OR REPLACE TABLE ALLSALES.ALLSALES_PART1 (
  ORDER_NUMBER STRING,
  SOURCE STRING,
  COMPANY STRING,
  SALES_DATE STRING,
  SALES_CHANNEL STRING,
  CURRENCY STRING,
  SALES_AGENT_ID STRING,
  STORE_ID STRING,
  PRODUCT STRING,
  ORDER_QTY STRING,
  UNIT_PRICE STRING,
  UNIT_COST STRING
)
COMMENT = 'Source file allsales_part1.csv, as is (2025 batch).';

COPY INTO ALLSALES.ALLSALES_PART1
FROM @ALLSALES.RAW_STAGE
FILES = ('allsales_part1.csv')
FILE_FORMAT = (FORMAT_NAME = 'ALLSALES.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- 3.2 Sales batch 2026 (20,000 rows expected) ---------------------------------
CREATE OR REPLACE TABLE ALLSALES.ALLSALES_PART2 (
  ORDER_NUMBER STRING,
  SOURCE STRING,
  COMPANY STRING,
  SALES_DATE STRING,
  SALES_CHANNEL STRING,
  CURRENCY STRING,
  SALES_AGENT_ID STRING,
  STORE_ID STRING,
  PRODUCT STRING,
  ORDER_QTY STRING,
  UNIT_PRICE STRING,
  UNIT_COST STRING
)
COMMENT = 'Source file allsales_part2.csv, as is (2026 batch).';

COPY INTO ALLSALES.ALLSALES_PART2
FROM @ALLSALES.RAW_STAGE
FILES = ('allsales_part2.csv')
FILE_FORMAT = (FORMAT_NAME = 'ALLSALES.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- 3.3 Sales team (31 rows expected) -------------------------------------------
CREATE OR REPLACE TABLE ALLSALES.ALLSALES_TEAM (
  COLUMN_1 STRING,
  INDEX STRING,
  SALES_TEAM STRING,
  REGION STRING
)
COMMENT = 'Source file allsales_team.csv, as is. Unnamed first column (COLUMN_1).';

COPY INTO ALLSALES.ALLSALES_TEAM
FROM @ALLSALES.RAW_STAGE
FILES = ('allsales_team.csv')
FILE_FORMAT = (FORMAT_NAME = 'ALLSALES.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- 3.4 Store locations (367 rows expected) -------------------------------------
CREATE OR REPLACE TABLE ALLSALES.ALLSALES_STORE (
  COLUMN_1 STRING,
  ID STRING,
  NAME STRING,
  COLONNE1 STRING,
  COUNTY STRING,
  REGION STRING,
  STATE_CODE STRING,
  STATE STRING,
  TYPE STRING,
  LATITUDE STRING,
  LONGITUDE STRING,
  AREA_CODE STRING,
  POPULATION STRING,
  HOUSEHOLDS STRING,
  MEDIAN_INCOME STRING,
  LAND_AREA STRING,
  WATER_AREA STRING,
  TIME_ZONE STRING,
  STATE_GEO STRING
)
COMMENT = 'Source file allsales_store.csv, as is. Unnamed first column (COLUMN_1) and extra columns.';

COPY INTO ALLSALES.ALLSALES_STORE
FROM @ALLSALES.RAW_STAGE
FILES = ('allsales_store.csv')
FILE_FORMAT = (FORMAT_NAME = 'ALLSALES.CSV_FORMAT_SEMICOLON')
ON_ERROR = 'CONTINUE';

-- =============================================================================
-- 4. ROW COUNT CHECKS (all 9 rows should return expected volumes)
-- =============================================================================
SELECT 'GDP.LIFE_EXPECTANCY'         AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 12744 AS EXPECTED FROM GDP.LIFE_EXPECTANCY
UNION ALL SELECT 'GDP.CONTINENT_MAPPING',        COUNT(*),     3 FROM GDP.CONTINENT_MAPPING
UNION ALL SELECT 'SUPERSTORE.SUPERSTORE_PART1',  COUNT(*),  3895 FROM SUPERSTORE.SUPERSTORE_PART1
UNION ALL SELECT 'SUPERSTORE.SUPERSTORE_PART2',  COUNT(*),  6105 FROM SUPERSTORE.SUPERSTORE_PART2
UNION ALL SELECT 'SUPERSTORE.NOMENCLATURE',      COUNT(*),    17 FROM SUPERSTORE.NOMENCLATURE
UNION ALL SELECT 'ALLSALES.ALLSALES_PART1',      COUNT(*), 20000 FROM ALLSALES.ALLSALES_PART1
UNION ALL SELECT 'ALLSALES.ALLSALES_PART2',      COUNT(*), 20000 FROM ALLSALES.ALLSALES_PART2
UNION ALL SELECT 'ALLSALES.ALLSALES_TEAM',       COUNT(*),    31 FROM ALLSALES.ALLSALES_TEAM
UNION ALL SELECT 'ALLSALES.ALLSALES_STORE',      COUNT(*),   367 FROM ALLSALES.ALLSALES_STORE;
